#!/usr/bin/env python3
"""
Demo script showing the booking and quote confirmation functionality.

This script demonstrates the booking workflow:
1. Customer submits a booking request
2. System generates a quote 
3. Customer confirms or rejects the quote
4. System updates quote status accordingly

Run this to see the booking flow in action.
"""

from datetime import datetime, timedelta
from enum import Enum
from typing import Optional


class QuoteStatus(str, Enum):
    """Status of quote in booking process."""
    PENDING = "pending"
    CONFIRMED = "confirmed"
    REJECTED = "rejected"
    EXPIRED = "expired"


class Quote:
    """Simple Quote class for demonstration."""
    def __init__(self, customer_name: str, customer_email: str, 
                 service_description: str, quoted_price: float,
                 currency: str = "USD", valid_until: Optional[datetime] = None,
                 status: QuoteStatus = QuoteStatus.PENDING, notes: Optional[str] = None):
        self.id = hash(customer_email + service_description) % 10000  # Simple ID generation
        self.customer_name = customer_name
        self.customer_email = customer_email
        self.service_description = service_description
        self.quoted_price = quoted_price
        self.currency = currency
        self.valid_until = valid_until or (datetime.utcnow() + timedelta(days=7))
        self.status = status
        self.notes = notes
        self.created_at = datetime.utcnow()
        self.confirmed_at = None

    def confirm(self):
        """Confirm the quote."""
        self.status = QuoteStatus.CONFIRMED
        self.confirmed_at = datetime.utcnow()
        print(f"✅ Quote #{self.id} confirmed at {self.confirmed_at.strftime('%Y-%m-%d %H:%M:%S')}")

    def reject(self):
        """Reject the quote."""
        self.status = QuoteStatus.REJECTED
        print(f"❌ Quote #{self.id} rejected")

    def display(self):
        """Display quote details."""
        print("\n" + "="*50)
        print(f"QUOTE #{self.id}")
        print("="*50)
        print(f"Customer: {self.customer_name}")
        print(f"Email: {self.customer_email}")
        print(f"Service: {self.service_description}")
        print(f"Price: ${self.quoted_price:.2f} {self.currency}")
        print(f"Valid Until: {self.valid_until.strftime('%Y-%m-%d %H:%M')}")
        print(f"Status: {self.status.value.upper()}")
        if self.notes:
            print(f"Notes: {self.notes}")
        if self.confirmed_at:
            print(f"Confirmed At: {self.confirmed_at.strftime('%Y-%m-%d %H:%M:%S')}")
        print("="*50)


def generate_quote(customer_name: str, customer_email: str, service_description: str) -> Quote:
    """Generate a quote based on service description."""
    # Simple pricing logic for demonstration
    base_price = 100.0
    length_multiplier = len(service_description) * 0.5
    quoted_price = base_price + length_multiplier
    
    notes = "Quote generated by CHB automated system. Final pricing subject to review."
    
    quote = Quote(
        customer_name=customer_name,
        customer_email=customer_email,
        service_description=service_description,
        quoted_price=quoted_price,
        notes=notes
    )
    
    return quote


def simulate_booking_workflow():
    """Simulate the complete booking workflow."""
    print("🏢 CHB BOOKING SYSTEM DEMONSTRATION")
    print("=" * 60)
    
    # Step 1: Customer submits booking request
    print("\n📝 STEP 1: Customer submits booking request")
    customer_name = "John Smith"
    customer_email = "john.smith@example.com"
    service_description = "Website development with responsive design and SEO optimization"
    
    print(f"Customer: {customer_name}")
    print(f"Email: {customer_email}")
    print(f"Service Requested: {service_description}")
    
    # Step 2: System generates quote
    print("\n💰 STEP 2: Generating quote...")
    quote = generate_quote(customer_name, customer_email, service_description)
    quote.display()
    
    # Step 3: Customer reviews and confirms quote
    print("\n🔍 STEP 3: Customer reviews quote")
    print("Customer is reviewing the quote details...")
    print("Customer decides to CONFIRM the quote")
    
    # Step 4: Quote confirmation
    print("\n✅ STEP 4: Quote confirmation")
    quote.confirm()
    quote.display()
    
    print("\n🎉 BOOKING WORKFLOW COMPLETED SUCCESSFULLY!")
    print("The customer has confirmed the quote and can proceed with the booking.")
    
    # Demonstrate rejection workflow
    print("\n" + "="*60)
    print("🔄 ALTERNATIVE WORKFLOW: Quote Rejection")
    print("="*60)
    
    # Create another quote
    quote2 = generate_quote("Jane Doe", "jane.doe@example.com", "Simple landing page")
    quote2.display()
    
    print("\n❌ Customer decides to REJECT this quote")
    quote2.reject()
    quote2.display()
    
    print("\nWorkflow completed. Customer can submit a new request if needed.")


if __name__ == "__main__":
    simulate_booking_workflow()